BINDIR := /usr/bin
JARDIR := /usr/lib/scraper

all:
	echo "Installing scraper"

install:
	mkdir -p ${DESTDIR}${BINDIR}
	mkdir -p ${DESTDIR}${JARDIR}/core
	mkdir -p ${DESTDIR}${JARDIR}/addons
	mkdir -p ${DESTDIR}${JARDIR}/plugins
	mkdir -p ${DESTDIR}${JARDIR}/nodes
	cp scraper ${DESTDIR}${BINDIR}/
	cp scraper-core.jar ${DESTDIR}${JARDIR}/core/

