JARDIR := /usr/lib/scraper

all:
	echo "Installing scraper persistent proxy scores plugin"

install:
	mkdir -p ${DESTDIR}${JARDIR}/plugins
	cp scraper-plugins-persistent-proxy-scores.jar ${DESTDIR}${JARDIR}/plugins/

